### ISSUE TITLE
Filtrer Instagram Copyright Claims Policy

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/france-elections-declarations#103]
Le filtrage effectué dans https://github.com/OpenTermsArchive/france-elections-versions/commit/cc9556f134a544beb709806333d8dae7d96c2a0a est correct, mais il semble être une conséquence d'un _update_ et non d'un _refilter_. Il faut s'assurer que le filtrage mène systématiquement à la version enregistrée.

**Comment by clementbiron** [comment]
Ce n'est pas un problème de filtrage ou de déclaration, c'est le snapshot qui alterne entre les versions mobile et desktop de ce document. 

La déclaration est faite pour la version desktop donc quand c'est le snapshot mobile on enregistre des éléments indésirables (le `select` fonctionne dans les deux versions).

Je mets ici une copie d'écran de la version mobile

![image](https://user-images.githubusercontent.com/364319/160623913-9c44a256-7fae-42c3-b82b-165636d5f6d6.png)

Il nous faudrait pouvoir forcer la version desktop avec un user agent, je crois que @martinratinaud avait une idée à ce sujet.

En attendant, je propose de supprimer les éléments indésirables de la version mobile pour `Copyright Claims Policy` et `Community Guidelines - Intellectual Property`, voir https://github.com/OpenTermsArchive/france-elections-declarations/pull/105

**Comment by MattiSG** [comment]
Le problème initial semble avoir été corrigé, mais le document a basculé en anglais : https://github.com/OpenTermsArchive/france-elections-versions/commit/cc27639ca0153586076af845722990c5dd23fe02

**Comment by MattiSG** [comment]
Nous n'arrivons pas à obtenir la version française du document sur https://help.instagram.com/454257084652404. C'est donc bien le contenu original qui est erroné.

**Comment by MattiSG** [comment]
Pour éviter du bruit, il faut donc filtrer la version anglaise en plus de la version française, en retirant les liens associés : https://github.com/OpenTermsArchive/france-elections-versions/commit/8e64570f5982b4b10c98e5c7ef370b50dc25e012

**Comment by MattiSG** [comment]
Le filtrage semble efficace 👍
